export { default as NavigationBar } from './NavigationBar'
export { default as HeroSection } from './Hero'
export { default as HowItWorksSection } from './HowItWorks'
export { default as PreviewOfWalletSection } from './PreviewOfWallet'
export { default as Footer } from './Footer'
